using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EasyMission.Domaine.Entity
{
    public enum Language
    {
        Espagnol, 
        anglais, 
        bengali,
        hindi,
        portugais,
        russe,
        japonais,
        allemand,
        javanais,
        coréen,
        français,
        vietnamien,
        telugu,
        chinois,
        marathi,
        tamoul,
        turc,
        ourdou,
        goudjarati,
        polonais,
        ukrainien,
        italien,
        malayalam,
        kannada,
        oriya,
        pendjabi,
        sunda,
        roumain,
        bhojpouri,
        farsi,
        maithili,
        haoussa,
        arabe,
        birman,
        serbe,
        awadhi,
        thaï,
        néerlandais,
        yorouba,
        sindhi,
        ouzbek,
        malais,
        amharique,
        indonésien,
        ibo,
        filipino,
        népali,
        saraiki,
        visayan,
        assamais,
        hongrois,
        chittagonian,
        madourais,
        singhalais,
        haryanvi,
        marwari,
        tchèque,
        grec,
        magahi,
        chhattisgarhi,
        deccan,
        biélorusse,
        zhuang,

    }
}
